export const SITE_TITLE: string = "San Phan";
export const SITE_DESCRIPTION: string =
  "Passionate frontend developer with 8 years of experience. Family man, book lover, and coding enthusiast. Join my blog for insights and fun";
export const X_ACCOUNT: string = "@sanphandinh";

export type Image = {
  src: string;
  alt?: string;
  caption?: string;
};

export type Link = {
  text: string;
  href: string;
};

export type Hero = {
  title?: string;
  text?: string;
  image?: Image;
  actions?: Link[];
};

export type SiteConfig = {
  title: string;
  subtitle?: string;
  description: string;
  image?: Image;
  headerNavLinks?: Link[];
  footerNavLinks?: Link[];
  socialLinks?: Link[];
  hero?: Hero;
};

const siteConfig: SiteConfig = {
  title: "San Phan",
  subtitle: "Personal blog",
  description:
    "Passionate frontend developer with 8 years of experience. Family man, book lover, and coding enthusiast. Join my blog for insights and fun",
  image: {
    src: "/ogp.png",
    alt: "Eclipse - Astro.js and Tailwind CSS theme",
  },
  headerNavLinks: [
    {
      text: "About",
      href: "/about",
    },
    // {
    //   text: "Projects",
    //   href: "/works",
    // },
    {
      text: "Blog",
      href: "/posts",
    },
  ],
  footerNavLinks: [
    {
      text: "Contact",
      href: "/contact",
    },
    // {
    //   text: "Terms",
    //   href: "/terms",
    // },
  ],
  socialLinks: [
    { href: "https://www.facebook.com/phandinhsan93/", text: "Facebook" },
    { href: "https://x.com/sanphandinh", text: "Twitter" },
    {
      href: "https://www.linkedin.com/in/san-phan-a2b467122/",
      text: "LinkedIn",
    },
    { href: "https://github.com/sanphandinh", text: "GitHub" },
  ],
  hero: {
    title: "My Journey",
    text: "Hello there! I'm a passionate frontend developer with 8 years of experience, currently crafting delightful user experiences at Moneyforward VN. My journey in the tech world has been an exciting rollercoaster, with stints at Onemount Company, Samsung VN, and a few dynamic startups.\n\nWhen I'm not immersed in code, I'm a family man at heart. I'm married to a wonderful partner, and we have a lovely daughter who brings endless joy to my life. Playing with her and my nephew is my favorite pastime, and I cherish every moment with them.\n\nIn my free time, you'll find me diving into books, manga, and movies, always on the lookout for new stories and adventures. My love for programming keeps me constantly exploring and learning, making every day a new opportunity to create something amazing.\n\nJoin me on this blog as I share my experiences, insights, and a bit of fun from my journey in the world of frontend development and beyond!",
    image: {
      src: "/hero.jpeg",
      alt: "My journey - generated by Bing Image creator",
      caption: "My journey - generated by Bing Image creator",
    },
    actions: [
      {
        text: "Get in Touch",
        href: "/contact",
      },
    ],
  },
};

export default siteConfig;
